### ISSUE TITLE
use nn.ModuleList

### ISSUE THREAD

**Issue by jekbradbury** [analvikingur/pytorch_Highway#1]
The `_add_to_parameters` method that you've used works, but there's actually a (fairly new) class in core PyTorch that does what you need here: [`nn.ModuleList`](http://pytorch.org/docs/nn.html#torch.nn.ModuleList). Similarly [`nn.ParameterList`](http://pytorch.org/docs/nn.html#torch.nn.ParameterList) does what you need in the TDNN implementation.

**Comment by kefirski** [comment]
Fixed
